name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          make -j
          ls -l *.nro

      - uses: actions/upload-artifact@v4
        with:
          name: SwitchSync_nro
          path: |
            SwitchSync.nro
            build/**/*
          if-no-files-found: error
