name: Build SwitchSync (.nro)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure toolchain
        shell: bash
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          dkp-pacman -Syu --noconfirm
          dkp-pacman -S --needed --noconfirm devkitA64 libnx switch-tools switch-cmake switch-pkg-config
          test -f "$DEVKITPRO/libnx/lib/libnx.a"

      - name: Build .nro
        shell: bash
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          make -j
          ls -l *.nro || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwitchSync_nro
          path: |
            SwitchSync.nro
            build/**/*
          if-no-files-found: error
