name: Build SwitchSync (.nro)

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure toolchain + libnx are present (idempotent)
      - name: Ensure devkitA64 + libnx
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          dkp-pacman -Syu --noconfirm
          dkp-pacman -S --needed --noconfirm devkitA64 libnx switch-tools switch-cmake switch-pkg-config
          # Confirm libnx exists (hard fail if missing)
          test -f "$DEVKITPRO/libnx/lib/libnx.a"
          ls -l "$DEVKITPRO/libnx/switch_rules"
          ls -l "$DEVKITPRO/libnx/lib/libnx.a"

      - name: Build .nro
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          # Normalize endings just in case
          perl -pi -e 's/\r\n/\n/g' Makefile
          find source -type f -name '*.cpp' -print0 | xargs -0 perl -pi -e 's/\r\n/\n/g'
          # Force the correct cross tools (avoid host ld)
          make -j \
            CC=/opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc \
            CXX=/opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++ \
            LD=/opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++
          ls -l *.nro || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwitchSync_nro
          path: |
            SwitchSync.nro
            build/**/*
          if-no-files-found: warn
      - name: Build .nro
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          perl -pi -e 's/\r\n/\n/g' Makefile
          # the -r makes xargs do nothing if there are no matches
          find source -type f \( -name '*.c' -o -name '*.cpp' \) -print0 | xargs -0 -r perl -pi -e 's/\r\n/\n/g'
          make -j
          ls -l *.nro || true
