name: Build SwitchSync (.nro)

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Make 100% sure toolchain + libnx are installed in the container
      - name: Ensure devkitA64 + libnx
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          dkp-pacman -Syu --noconfirm
          dkp-pacman -S --needed --noconfirm devkitA64 libnx switch-tools switch-cmake switch-pkg-config
          which aarch64-none-elf-g++
          ls -l "$DEVKITPRO/libnx/switch_rules" || true
          ls -la "$DEVKITPRO/libnx/lib" || true

      - name: Build .nro
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          # Normalize endings just in case
          perl -pi -e 's/\r\n/\n/g' Makefile
          find source -type f -name '*.cpp' -print0 | xargs -0 perl -pi -e 's/\r\n/\n/g'
          # Force the correct cross tools so we never call host 'ld'
          make -j \
            CC=aarch64-none-elf-gcc \
            CXX=aarch64-none-elf-g++ \
            LD=aarch64-none-elf-g++
          ls -l *.nro || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwitchSync_nro
          path: |
            SwitchSync.nro
            build/**/*
          if-no-files-found: warn
