name: Build SwitchSync (.nro)

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build .nro
        run: |
          . /etc/profile.d/devkit-env.sh
          make -j
          ls -l *.nro || true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwitchSync_nro
          path: |
            SwitchSync.nro
            build/**/*
          if-no-files-found: warn
