name: Build SwitchSync (.nro)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # No pacman, no updates, no network. Just verify what's already in the image.
      - name: Check toolchain (offline)
        shell: bash
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          echo "DEVKITPRO=$DEVKITPRO"
          ls -l "$DEVKITPRO/libnx/lib/libnx.a"
          aarch64-none-elf-gcc --version

      - name: Build .nro
        shell: bash
        run: |
          set -e
          . /etc/profile.d/devkit-env.sh
          make -j
          ls -l *.nro || (echo "No NRO produced"; exit 1)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwitchSync_nro
          path: |
            SwitchSync.nro
            build/**/*
          if-no-files-found: error

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwitchSync_nro
          path: |
            SwitchSync.nro
            build/**/*
          if-no-files-found: error
